name: Run Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Newman and wait-on
        run: npm install -g newman wait-on

      - name: Start application in background
        run: |
          node shopping-store-linux-amd64 &

      - name: Wait for application to be ready
        run: |
          wait-on http://localhost:2221  # Replace with your app's real URL

      - name: Run Postman Collection
        run: |
          newman run collection.json
